# -*- coding: utf-8 -*-
"""Ejercicios para Alumnos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPYjDN7YFpw1UbwcxAdsbBXTWNGovzCd
"""

# Ejercicios de Práctica: Fundamentos de Python
# IT - Primer Año

# --------------------------------------------------------------------------
# Ejercicio 0: Ver, Pensar, Preguntar
#
# Instrucciones:
# Lee el siguiente código. No lo ejecutes todavía.
# Piensa: ¿Qué crees que aparecerá en la consola cuando se ejecute?
# --------------------------------------------------------------------------

producto = "Laptop Gamer"
precio = 15000.50
stock = 10
es_oferta = (precio < 20000)
print(f"Producto: {producto}")
print(f"¿Está en stock? {stock > 0}")
print(f"¿Es una buena oferta? {es_oferta}")

# --------------------------------------------------------------------------
# Ejercicio 1: Calculadora de Edad
#
# Instrucciones:
# 1. Pide al usuario que ingrese su año de nacimiento.
# 2. Guarda ese valor en una variable.
# 3. Recuerda que input() siempre devuelve un texto. ¡Necesitas convertirlo a número!
# 4. Calcula la edad aproximada restando el año de nacimiento del año actual.
# 5. Muestra la edad en un mensaje claro, por ejemplo: "Tienes X años."
# --------------------------------------------------------------------------

# Escribe tu código aquí

nacimiento = int(input("Ingresa Tu Año de Nacimiento:\n"))
actual = 2025
edad = round((actual - nacimiento),1)
print(f"Tienes {edad} años" )

# --------------------------------------------------------------------------
# Ejercicio 2: Convertidor de Moneda Simple
#
# Instrucciones:
# 1. Define una variable `tasa_de_cambio_usd_a_mxn` con un valor fijo (ej. 17.50).
# 2. Pide al usuario que ingrese una cantidad en dólares (USD).
# 3. Convierte esa cantidad a un número (puede tener decimales, así que usa float()).
# 4. Calcula el equivalente en pesos mexicanos (MXN).
# 5. Muestra el resultado en un mensaje claro, ej: "XX.XX USD equivalen a YY.YY MXN."
# --------------------------------------------------------------------------

# Escribe tu código aquí
dolares = float(input("Ingresa la Cantidad de dolares que tienes: \n"))
tasa_de_cambio_usd_a_mxn = 17.5
pesosmx = tasa_de_cambio_usd_a_mxn * dolares
print(f"{dolares} USD equivalen a {pesosmx} MXN.")

# --------------------------------------------------------------------------
# Ejercicio 3: Verificador de Acceso
#
# Instrucciones:
# 1. Pide al usuario su edad (puedes reutilizar parte del código del Ejercicio 1).
# 2. Usa una estructura `if/else` para determinar si es mayor de edad.
# 3. Si la edad es 18 o más, muestra el mensaje: "Acceso concedido. ¡Bienvenido!".
# 4. Si es menor de 18, muestra el mensaje: "Acceso denegado. Debes ser mayor de edad."
# --------------------------------------------------------------------------

# Escribe tu código aquí

nacimiento = int(input("Ingresa Tu Año de Nacimiento:\n"))
actual = 2025
edad = round((actual - nacimiento),1)

if edad >= 18:
    print(f"Tienes: {edad} años Acceso concedido. ¡Bienvenido!")

else:
    print(f"Tienes: {edad} años Acceso denegado. Debes ser mayor de edad.")

# --------------------------------------------------------------------------
# Ejercicio 4: Clasificador de Números
#
# Instrucciones:
# 1. Pide al usuario que ingrese un número entero.
# 2. Usando `if`, `elif` y `else`, determina si el número es:
#    - Positivo
#    - Negativo
#    - O exactamente cero
# 3. Muestra un mensaje apropiado para cada caso.
#    Ej: "El número es positivo."
# --------------------------------------------------------------------------

# Escribe tu código aquí

numero = int(input("Ingresa un Numero entero: \n"))

if numero > 0:
    print("El numero es positivo")

elif numero < 0:
    print("El numero es negativo")

else:
    print("El numero es Igual a cero")

# --------------------------------------------------------------------------
# Ejercicio 5: Desafío - Mini Calculadora
#
# Instrucciones:
# 1. Pide al usuario un primer número.
# 2. Pide al usuario un segundo número.
# 3. Pide al usuario que elija una operación escribiendo una palabra:
#    "suma", "resta", "multiplicacion" o "division".
# 4. Usa condicionales (`if/elif/else`) para verificar qué operación eligió.
# 5. Realiza el cálculo correspondiente y muestra el resultado.
# 6. ¡Reto extra! Si la operación es "division" y el segundo número es 0,
#    muestra un mensaje de error como "Error: No se puede dividir por cero."
#    en lugar de realizar la operación.
# --------------------------------------------------------------------------

# Escribe tu código aquí


# Desafío 6 (Corregido)

# Declaración de variables globales para almacenar los números
num_1 = 0
num_2 = 0

# --- Funciones de Ingreso y Operación ---


def obtener_numeros():
    global num_1, num_2
    while True:
        try:
            print("\n--- INGRESO DE NÚMEROS ---")
            num_1 = float(input("➡️ Ingrese su primer número: "))
            num_2 = float(input("➡️ Ingrese su segundo número: "))
            break  # Salir del bucle si los datos son correctos
        except ValueError:
            print(" ERROR: Ingrese un dato correcto (solo números).")


def sumar(a, b):
    print(f"La suma de {a} + {b} = {a + b}")


def resta(a, b):
    print(f"La resta de {a} - {b} = {a - b}")


def division(a, b):
    if b == 0:
        print(" ERROR: No se puede dividir entre 0.")
    else:
        print(f"La división de {a} / {b} = {a / b}")


def multiplicacion(a, b):
    print(f"La multiplicación de {a} * {b} = {a * b}")

# --- Función de Menú y Selección ---


def mostrar_menu_de_operaciones():
    print("\n--- MENÚ DE OPERACIONES ---")
    print("1. Suma (+)")
    print("2. Resta (-)")
    print("3. Multiplicación (*)")
    print("4. División (/)")
    print("5. Salir")
    print("----------------------------")

    while True:
        opcion = input("✏️ Escoga una operación (1-5): ")
        # Corregido: La opción '3' (Multiplicación) ahora está incluida.
        if opcion in ['1', '2', '3', '4', '5']:
            return opcion
        else:
            print(" Opción inválida. Intente de nuevo.")

# --- Función Principal de la Calculadora ---


def calculadora():
    # 1. Obtener los números del usuario (solo una vez)
    obtener_numeros()

    # 2. Bucle principal para el menú (while True)
    while True:
        # Obtener la opción del menú
        opcion = mostrar_menu_de_operaciones()

        # 3. Opción de salida
        if opcion == '5':
            print("👋 Gracias por usar la calculadora. ¡Adiós!")
            break

        print(f"\n Operando con: {num_1} y {num_2}")

        # 4. Ejecución de la operación
        if opcion == '1':
            sumar(num_1, num_2)
        elif opcion == '2':
            resta(num_1, num_2)
        elif opcion == '3':
            multiplicacion(num_1, num_2)
        elif opcion == '4':
            division(num_1, num_2)


# Ejecutar el programa
calculadora()